server:
  port: 6000
keycloak:
  auth-server-url: http://127.0.0.1/auth
  realm: accounting
  resource: accounting-client
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  ssl-required: external
accounting_server:
  datasource:
    accounting_postgres_data_source:
      url: jdbc:postgresql://127.0.0.1:5432/accounting_db
      username: accounting_user
      password: accounting_db_123
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
accounting:
  auth-enabled: false